### PR TITLE
Add Tests

### LINKED ISSUE #8: Add Tests
Add tests to plugin.

Comments from #4 for reference:

> Use the `github.com/google/go-tpm-tools/simulator` package.

> Load an EK Cert into the simulator. This project does it with bash, just need to figure out what those commands would be in Go: https://github.com/mrcdb/tpm2_ek_cert_generator

Once `tpm2-tools` supports `tpm2tools.StoreEKCert` and `tpm2tools.EKCertTemplate`, the functionality from https://github.com/mrcdb/tpm2_ek_cert_generator could be ported to go, see https://github.com/bloomberg/spire-tpm-plugin/issues/4#issuecomment-621693593

### PR DESCRIPTION
**Pull request by caleblloyd**
Fixes #8 

**Describe your changes**

1. Move agent/server logic to `pkg` to allow for tests to call into library
2. Add `common_test` pkg for test utilities that:
  - Load EKCert using modified version of https://github.com/mrcdb/tpm2_ek_cert_generator
  - Expose the simulator over TCP to allow `tpm2-tools` commands to interface with simulator
  - Interface with `go-attest` through CommandChannel
3. Add GitHub Actions
4. Add tests

**Testing performed**

1. `pkg/agent/plugin_test.go`: end-to-end plugin test adapted from Spire's [node test](https://github.com/spiffe/spire/blob/62e723fafafe322cb68e4d494d96cb29695a7b37/pkg/agent/attestor/node/node_test.go).  This test exists in the `agent` pkg because it passes the simulator to the agent in a private `tpm` object
2. `tools/get_tpm_pubhash/get_tpm_pubhash_test.go`: start TPM simulator, load EK Cert, get EK hash out and confirm it matches

### CODE REVIEW

**Comment by caleblloyd** [comment]
Test output in GH Actions from fork: https://github.com/boxboat/spire-tpm-plugin/runs/657685699

**Comment by pawalt** [comment]
Hey Caleb, thanks for the PR! This is very exciting. I'm going to need a bit to look everything over, but I'll get to this ASAP.

**Comment by pawalt** [comment]
@caleblloyd I've looked through this and largely things look good. Could you comment up the files in the `common_test` dir though? I can understand everything else pretty easily, but that took a while to parse. Also, we use travis for our CI so if you remove that Github Actions file I can merge this in and then add in Travis myself.

**Comment by caleblloyd** [comment]
Sure, I will add the comments.

I can remove GH Actions, but I also added automated releases that I was going to send as a follow-up PR: https://github.com/boxboat/spire-tpm-plugin/commit/a916f7dba47151723820fe2ae7c8ad172321d555, they are pretty convenient.  Just push a tag and GH Actions will create the tarball and upload it to the release.  Let me know if you think that would be better than re-implementing in Travis.

**Comment by pawalt** [comment]
We've standardized around Travis for all our projects, so barring something becoming impossible to do in Travis, it would be more work to set up & automate management of a new CI system than to than to do the thing in Travis.

Comments look good, so if you can remove the GH actions file, I'll merge this in.

**Comment by caleblloyd** [comment]
:+1: GH Actions removed

**Review by pawalt — APPROVED** [review]
Let's get that merge

**Pull request merged**
